name: magic_clash
description: "跨平台 Mihomo 核心启动器"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  dio: ^5.4.0
  json_annotation: ^4.8.0
  path_provider: ^2.1.0
  path: ^1.9.0
  shared_preferences: ^2.2.0
  fl_chart: ^0.68.0
  window_manager: ^0.3.0
  archive: ^3.4.0
  file_picker: ^8.0.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
